# Generated by Django 3.1.5 on 2021-01-14 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_on',
        ),
    ]
